api/urls.py
#!CenecuWeb/api/urls.py
"""Rutas del API"""

from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from .views import HorarioView, CursoView, ProfesorView, CursoProfesorView
from .views import AreaView, AnuncioView, FraseView, GoalsListView
from .views import AreaInteresView, UsuarioRolView, NotaView, TelefonosEdit
from .views import ContenidoCompartidoView, RegistroUsuarioCursoView

from .views import TelefonosView, HorarioEdit, CursoEdit, ProfesorEdit
from .views import CursoProfesorEdit, AreaEdit, AnuncioEdit, FraseEdit
from .views import GoalsListEdit, AreaInteresEdit, UsuarioRolEdit
from .views import NotaEdit, ContenidoCompartidoEdit, RegistroUsuarioCursoEdit
from . import views

from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_jwt.views import verify_jwt_token


urlpatterns = {
    url(r'^$', views.api_index, name="Index"),
    url(r'^Horario/$', HorarioView.as_view(), name="Horario"),
    url(r'^Curso/$', CursoView.as_view(), name="Curso"),
    url(r'^Profesor/$', ProfesorView.as_view(), name="Profesor"),
    url(r'^CursoProfesor/$', CursoProfesorView.as_view(),
        name="CursoProfesor"),
    url(r'^Area/$', AreaView.as_view(), name="Area"),
    url(r'^Anuncio/$', AnuncioView.as_view(), name="Anuncio"),
    url(r'^Frase/$', FraseView.as_view(), name="Frase"),
    url(r'^GoalsList/$', GoalsListView.as_view(), name="GoalsList"),
    url(r'^AreaInteres/$', AreaInteresView.as_view(), name="AreaInteres"),
    url(r'^UsuarioRol/$', UsuarioRolView.as_view(), name="UsuarioRol"),
    url(r'^Nota/$', NotaView.as_view(), name="Nota"),
    url(r'^ContenidoCompartido/$', ContenidoCompartidoView.as_view(),
        name="ContenidoCompartido"),
    url(r'^RegistroUsuarioCurso/$', RegistroUsuarioCursoView.as_view(),
        name="RegistroUsuarioCurso"),
    url(r'^Telefonos/$', TelefonosView.as_view(), name="Telefonos"),

    url(r'^Horario/(?P<pk>[0-9]+)/$', HorarioEdit.as_view(),
        name="HorarioEdit"),
    url(r'^Curso/(?P<pk>[0-9]+)/$', CursoEdit.as_view(),
        name="CursoEdit"),
    url(r'^Profesor/(?P<pk>[0-9]+)/$', ProfesorEdit.as_view(),
        name="ProfesorEdit"),
    url(r'^CursoProfesor/(?P<pk>[0-9]+)/$', CursoProfesorEdit.as_view(),
        name="CursoProfesorEdit"),
    url(r'^Area/(?P<pk>[0-9]+)/$', AreaEdit.as_view(), name="AreaEdit"),
    url(r'^Anuncio/(?P<pk>[0-9]+)/$', AnuncioEdit.as_view(),
        name="AnuncioEdit"),
    url(r'^Frase/(?P<pk>[0-9]+)/$', FraseEdit.as_view(), name="FraseEdit"),
    url(r'^GoalsList/(?P<pk>[0-9]+)/$', GoalsListEdit.as_view(),
        name="GoalsListEdit"),
    url(r'^AreaInteres/(?P<pk>[0-9]+)/$', AreaInteresEdit.as_view(),
        name="AreaInteresEdit"),
    url(r'^UsuarioRol/(?P<pk>[0-9]+)/$', UsuarioRolEdit.as_view(),
        name="UsuarioRolEdit"),
    url(r'^Nota/(?P<pk>[0-9]+)/$', NotaEdit.as_view(), name="NotaEdit"),
    url(r'^ContenidoCompartido/(?P<pk>[0-9]+)/$',
        ContenidoCompartidoEdit.as_view(), name="ContenidoCompartidoEdit"),
    url(r'^RegistroUsuarioCurso/(?P<pk>[0-9]+)/$',
        RegistroUsuarioCursoEdit.as_view(), name="RegistroUsuarioCursoEdit"),
    url(r'^Telefonos/(?P<pk>[0-9]+)/$', TelefonosEdit.as_view(),
        name="TelefonosEdit"),

    url(r'^Hello/$', views.hello_world, name="testOverride"),
    url(r'^loginCenecu/$', views.login_cenecu, name="login"),
    url(r'^notasUser/(?P<pk>[0-9]+)/$', views.notas_por_user,
        name="notas_por_user"),
    url(r'^borrarNota/(?P<pk>[0-9]+)/$', views.borrar_nota, name="borrar_nota"),
    url(r'^cumplirNota/(?P<pk>[0-9]+)/$', views.cumplir_nota, name="cumplir_nota"),
    url(r'^registrarUsuario/$', views.registrar_usuario,
        name="registrar_usuario"),
    url(r'^horarioPorCurso/(?P<pk>[0-9]+)/$',views.horarios_por_curso, name="horario_por_curso"),
    url(r'^logOut/$', views.log_out, name="log_out"),
    url(r'^horariosPorCurso/(?P<pk>[0-9]+)/$', views.horarios_por_curso, name="horarios_por_curso"),

    url(r'^auth-jwt/', obtain_jwt_token),
    url(r'^auth-jwt-refresh/', refresh_jwt_token),
    url(r'^auth-jwt-verify/', verify_jwt_token),
    url(r'^get-user/', views.get_user, name="user_info"),
    url(r'^cambioPass/', views.cambiar_pass, name="cambiar_pass"),

}

urlpatterns = format_suffix_patterns(urlpatterns)

cenecu_admin/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from django.contrib.auth.views import login
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index , name = 'index'),
    url(r'^login/$', views.iniciar_sesion, name='iniciar_sesion'),
    url(r'^nuevoCurso/$',views.nuevo_curso, name='nuevo_curso' ),
    url(r'^crearCurso/$',views.crear_curso,name='crear_curso'),
    url(r'^editarCurso/(?P<pk>[0-9]+)', views.editar_curso, name='editar_curso'),
    url(r'^modificarCurso/$',views.modificar_curso,name='modificar_curso'),
    url(r'^eliminarCurso/(?P<pk>[0-9]+)$', views.eliminar_curso, name='eliminar_curso'),
    url(r'^listarProfesores/$', views.listar_profesores , name = 'listar_profesores'),
    url(r'^nuevoProfesor/$',views.nuevo_profesor, name='nuevo_profesor'),
    url(r'^crearProfesor/$',views.crear_profesor, name='crear_profesor' ),
    url(r'^editarProfesor/(?P<pk>[0-9]+)', views.editar_profesor, name='editar_profesor'),
    url(r'^modificarProfesor/$',views.modificar_profesor,name='modificar_profesor'),
    url(r'^eliminarProfesor/(?P<pk>[0-9]+)$', views.eliminar_profesor, name='eliminar_profesor'),
    url(r'^listarAnuncios/$', views.listar_anuncios , name = 'listar_anuncios'),
    url(r'^nuevoAnuncio/$',views.nuevo_anuncio, name='nuevo_anuncio'),
    url(r'^crearAnuncio/$',views.crear_anuncio, name='crear_anuncio' ),
    url(r'^editarAnuncio/(?P<pk>[0-9]+)', views.editar_anuncio, name='editar_anuncio'),
    url(r'^modificarAnuncio/$',views.modificar_anuncio,name='modificar_anuncio'),
    url(r'^eliminarAnuncio/(?P<pk>[0-9]+)$', views.eliminar_anuncio, name='eliminar_anuncio'),
    url(r'^listarFrases/$', views.listar_frases , name = 'listar_frases'),
    url(r'^nuevaFrase/$',views.nueva_frase, name='nueva_frase'),
    url(r'^crearFrase/$',views.crear_frase, name='crear_frase' ),
    url(r'^editarFrase/(?P<pk>[0-9]+)', views.editar_frase, name='editar_frase'),
    url(r'^modificarFrase/$',views.modificar_frase,name='modificar_frase'),
    url(r'^eliminarFrase/(?P<pk>[0-9]+)$', views.eliminar_frase, name='eliminar_frase'),
    url(r'^listarAreas/$', views.listar_areas , name = 'listar_areas'),
    url(r'^nuevaArea/$',views.nueva_area, name='nueva_area'),
    url(r'^crearArea/$',views.crear_area, name='crear_area' ),
    url(r'^editarArea/(?P<pk>[0-9]+)', views.editar_area, name='editar_area'),
    url(r'^modificarArea/$',views.modificar_area, name='modificar_area'),
    url(r'^eliminarArea/(?P<pk>[0-9]+)$', views.eliminar_area, name='eliminar_area'),
    url(r'^reportes/$',views.visualizar_reporte, name='visualizar_reporte'),
    url(r'^reporteArea/$', views.reporte_user_area_interes, name='reporte_area'),
    url(r'^reporteSolicitud/$', views.reporte_user_solicitud_registro, name='reporte_solicitud'),
    url(r'^refresh/$', views.ajaxReporteCompartido, name='ajaxReporteCompartido'),
    url(r'^seleccionCurso/$', views.visualizar_reporte_compartido, name='visualizar_reporte_compartido'),
    url(r'^seleccionCurso/(?P<pk>[0-9]+)$', views.reporte_curso_compartido, name='reporte_curso_compartido'),    
    url(r'^reporteCurso/(?P<pk>[0-9]+)$', views.reporte_curso_compartido, name='reporte_curso_compartido'),
    url(r'^exportarReporte/$',views.exportar_repo, name='exportar_reporte'),
    url(r'^logout/$',views.cerrar_sesion, name='cerrar_sesion'),
    url(r'^exportar/Reporte/(?P<reporte>[0-9]+)/(?P<curso>[0-9]+)$',views.reportes_xlsx, name='reportes_xlsx'),

    
]

cenecu_web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('api.urls')),
    url(r'^', include('cenecu_admin.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
#!CenecuWeb/api/models.py
"""Definicion de modelos para crear la base de datos"""

from django.db import models
from django.contrib.auth.models import User


class Horario(models.Model):
    """Horarios de cursos en dia de las semanas"""

    dias_semana = (('L', 'Lunes'), ('M', 'Martes'), ('Mi', 'Miercoles'),
                   ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado'))

    curso_id = models.ForeignKey('Curso', on_delete=models.CASCADE)
    dia = models.CharField(max_length=2, blank=False, choices=dias_semana)
    hora_inicio = models.IntegerField()
    minutos_inicio = models.IntegerField()
    hora_fin = models.IntegerField()
    minutos_fin = models.IntegerField()

    def __str__(self):
        return "{}".format(self.dia)


class Curso(models.Model):
    """Cursos de cenecu"""

    tipo_duracion = (('S', 'Semanas'), ('M', 'Meses'))
    nombre = models.CharField(max_length=100, blank=False)
    descripcion = models.CharField(max_length=255, blank=False)
    pensum = models.FileField(upload_to='uploads/pensums/')
    duracion_cant = models.IntegerField()
    duracion_tipo = models.CharField(max_length=1, blank=False,
                                     choices=tipo_duracion)
    costo = models.FloatField()
    img_curso = models.ImageField(upload_to='uploads/imagenes/')
    area_estudio = models.ForeignKey('Area', on_delete=models.CASCADE)
    estado = models.CharField(max_length=10, blank=False)
    fecha_creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.nombre)


class Profesor(models.Model):
    """Profesores de cenecu"""

    nombre = models.CharField(max_length=16, blank=False)
    apellido = models.CharField(max_length=16, blank=False)
    titulo = models.CharField(max_length=20, blank=False)
    img_perfil = models.ImageField(upload_to='uploads/fotoProfesores/')
    frases_personal = models.CharField(max_length=100, blank=False)
    biografia = models.CharField(max_length=255, blank=False)
    area_especializacion = models.ForeignKey('Area', on_delete=models.CASCADE)
    url_linkedin = models.CharField(max_length=255, blank=False)
    curriculum = models.FileField(upload_to='uploads/pensums/')
    estado = models.CharField(max_length=10, blank=False)
    fecha_creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.nombre)


class CursoProfesor(models.Model):
    """Relacion entre profesor y curso a dictar"""

    curso_id = models.ForeignKey('Curso', on_delete=models.CASCADE)
    profesor_id = models.ForeignKey('Profesor', on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.curso_id)


class Area(models.Model):
    """Areas de interes de cenecu"""

    nombre = models.CharField(max_length=25, blank=False)
    descripcion = models.CharField(max_length=100)
    img_area = models.ImageField(upload_to='uploads/areas/')
    estado = models.CharField(max_length=10, blank=False)

    def __str__(self):
        return "{}".format(self.nombre)


class Anuncio(models.Model):
    """Anuncios y promociones de cenecu"""

    descripcion = models.CharField(max_length=255, blank=False)
    img_anuncio = models.ImageField(upload_to='uploads/anuncio/')
    fecha_limite = models.DateField()
    estado = models.CharField(max_length=10, blank=False)
    fecha_creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "anuncio: " + self.descripcion


class Frase(models.Model):
    """Frases motivacionales de cenecuApp"""

    descripcion = models.CharField(max_length=100, blank=False)
    img_frase = models.ImageField(upload_to='uploads/frase/')
    estado = models.CharField(max_length=10, blank=False)
    fecha_creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.descripcion)


class GoalsList(models.Model):
    """GoalList"""

    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)
    curso_id = models.ForeignKey('Curso', on_delete=models.CASCADE)
    estado = models.CharField(max_length=10, blank=False)
    fecha_creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.curso_id)


class AreaInteres(models.Model):
    """Areas de Interes de los usuarios"""

    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)
    area_id = models.ForeignKey('Area', on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.area_id)


class UsuarioRol(models.Model):
    """Roles de los usuarios"""

    roles = (('cliente', 'cliente'), ('admin', 'administrador'),
             ('bloqueado', 'UsuarioBloqueado'))
    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)
    rol = models.CharField(max_length=10, blank=False, choices=roles)

    def __str__(self):
        return "{}".format(self.usuario_id)


class Nota(models.Model):
    """Notas de los usuarios"""

    titulo = models.CharField(max_length=100, blank=False)
    descripcion = models.CharField(max_length=255)
    fecha_limite = models.DateField()
    notificacion = models.BooleanField()
    fecha_notificacion = models.DateTimeField()
    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)
    estado = models.CharField(max_length=10, blank=False)
    fecha_creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.titulo)


class ContenidoCompartido(models.Model):
    """Contenido compartido por las redes sociales"""

    rsocial = (('tw', 'Twitter'), ('wa', 'Whatsapp'), ('fb', 'Facebook'))
    curso_id = models.ForeignKey('Curso', on_delete=models.CASCADE)
    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_compartido = models.DateTimeField(auto_now_add=True)
    red_social = models.CharField(max_length=2, blank=False, choices=rsocial)

    def __str__(self):
        return "{}".format(self.red_social)


class RegistroUsuarioCurso(models.Model):
    """Solicitudes de registro a un curso"""

    curso_id = models.ForeignKey('Curso', on_delete=models.CASCADE)
    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_solicitud = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.curso_id)


class Telefonos(models.Model):
    """Telefonos de los usuarios"""

    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE)
    telefonos = models.CharField(max_length=12, blank=False)

    def __str__(self):
        return "{}".format(self.telefonos)

cenecu_admin/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

cenecu_admin/templates/cenecu_admin/crear_anuncio.html
{% extends "cenecu_admin/base.html" %}
{% load static %}
{% block titulo %} Crear anuncio {% endblock %}

{% block contenido %}
<!-- Permite la creación de información de un anuncio -->
<div class="col-lg-12" >
  <div class="card">
    <div class="card-body formulario">
      <h2 >Crear un nuevo anuncio publicitario</h2>
      <br>
      <br>
  
    <!-- Campos de un anuncio -->
    <div class="form-validation">
      <form id="nuevoAnuncio-form"class="form-valide" action="{% url 'nuevo_anuncio' %}"
          method="post"  enctype="multipart/form-data"> {% csrf_token %}
          
        <div class="form-group row">
          <label class="col-lg-2 col-form-label" for="descripcion">
            Descripción<span class="text-danger">*</span></label>
          <div class="col-lg-8">
            <textarea rows="10" 
            cols="50" class="form-control alfanumerico" id="descripcion"
            name="descripcion" maxlength="256" 
            placeholder="Ingrese la descripción del anuncio" 
            required onkeydown="validarLetrasNumeros(event)"></textarea>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-lg-2 col-form-label" for="img_anuncio">
            Imagen<span class="text-danger">*</span></label>
          <div class="col-lg-8">
            <input type="FILE" class="form-control" id="img_anuncio" 
              name="img_anuncio" required onchange="validarFormatoImagen()"
              accept="image/jpg, image/jpeg, image/png">
          </div>
        </div>

        <div class="form-group row">
          <label class="col-lg-2 col-form-label" for="fecha_limite">
            Fecha Límite</label>
            <div class="col-lg-2">
              <input type="date" class="form-control" id="fecha_limite" name="fecha_limite" min="">
            </div>  
        </div>

        <div class="form-group row" hidden>
          <label class="col-lg-2 col-form-label" for="estado">
            Estado<span class="text-danger">*</span></label>
          <div class="col-lg-8">
            <select class="form-control" id="estado" name="estado">
              <option value="Activo">Activo</option>
              <option value="Inactivo">Inactivo</option>
            </select>
          </div>
        </div>
        <br />
        <br />
        <!-- Botón para agregar una nuevo anuncio-->
        <div class="form-group row">
          <div class="col-lg-12 " align="center">
              <button type="submit" class="btn btn-success">Crear</button>
              <button type="button" class="btn btn-primary" onclick="resetForm()">Limpiar</button>
          </div>
        </div>
        
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extraScript %}
  <script src="/static/js/scripts/anuncios.js"></script>
{% endblock %}

cenecu_admin/templates/cenecu_admin/crear_area.html
{% extends "cenecu_admin/base.html" %}
{% load static %}
{% block titulo %} Crear Área {% endblock %}
{% block contenido %}

<!-- Permite la creación de información de un área de interés -->

<div class="col-lg-12" >
  <div class="card">
    <div class="card-body formulario">
      <h2>Crear una nueva área de interés</h2>
      <br >
      <br >
      <!-- Campos de un área de interés -->
  
    <div class="form-validation">
      <form  id="nuevoArea-form" class="form-valide" action="{% url 'nueva_area' %}"
          method="post"  enctype="multipart/form-data"> {% csrf_token %}
        
        <div class="form-group row">
          <label class="col-lg-2 col-form-label" for="nombreArea">
            Nombre<span class="text-danger">*</span></label>
          <div class="col-lg-8">
            <input type="text" class="form-control letras" id="nombreArea" 
              name="nombreArea" maxlength="30"
              placeholder="Ingrese el nombre del área de interés" 
              required onkeydown="validarLetras(event)">
          </div>
        </div>

        <div class="form-group row">
          <label class="col-lg-2 col-form-label" for="descripcion">
            Descripción<span class="text-danger">*</span></label>
          <div class="col-lg-8">
            <textarea rows="10" 
            cols="50" class="form-control alfanumerico" id="descripcion"
            name="descripcion" maxlength="256" 
            placeholder="Ingrese la descripción del anuncio" 
            required onkeydown="validarLetrasNumeros(event)"></textarea>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-lg-2 col-form-label" for="img_area">
            Imagen<span class="text-danger">*</span></label>
          <div class="col-lg-8">
            <input type="FILE" class="form-control" id="img_area" 
              name="img_area" required onchange="validarFormatoImagen()"
              accept="image/jpg, image/jpeg, image/png">
          </div>
        </div>

        <div class="form-group row" hidden>
          <label class="col-lg-2 col-form-label" for="estado">
            Estado<span class="text-danger">*</span></label>
          <div class="col-lg-8">
            <select class="form-control" id="estado" name="estado">
              <option value="Activo">Activo</option>
              <option value="Inactivo">Inactivo</option>
            </select>
          </div>
        </div>
        <br >   
        <br >             
        
        <!-- Botón para agregar una nueva área de interes-->
       <div class="form-group row">
          <div class="col-lg-12 " align="center">
              <button type="submit" class="btn btn-success">Crear</button>
              <button type="button" class="btn btn-primary" onclick="resetForm()">Limpiar</button>
          </div>
      </div>
        
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extraScript %}
  <script src="/static/js/scripts/areas.js"></script>
  <script src="/static/js/scripts/refactoring1.js"></script>
{% endblock %}

cenecu_admin/templates/cenecu_admin/reporte_usuario_solicitud.html
{% extends "cenecu_admin/base.html" %}
{% load static %}
{% block titulo %} Reportes {% endblock %}
{% block extraStyle %}


 <style type="text/css">
     .btn-repo{
        margin-bottom: 4px;
     }

     .div-reportes{
        margin: 20px;
        margin-left: 20px;
    }

    option{
        margin: 2px;
    }

    .rep-div{
        margin-bottom: 25px; 
    }

    .rep-grafico{
        width: 80%;
    }

 </style>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<script src="{% static 'js/reporte.js' %}"></script>

<script type="text/javascript">
</script>

{% endblock %}
{% block contenido %}
<div class="reporte reporte-solicitud-registro">
    <div class="col-lg-12" >
        <div class="card" align="center" >
            <div class="card-body">
                <h3 style="text-align: center; margin-bottom: 5px">Cantidad de Solicitudes de Registros por Curso</h3>
                 {% if total_cursos == 0 %}
                    <h4 style="color: red; text-align: center"> No existen solicitudes de registro en los ultimos 30 dias</h4>
                 {% else %}
                <div class="rep-div rep-grafico">
                     <canvas id="grafico-solicitudes-registro" width="500px"></canvas>
                        <script>
                        var ctx = document.getElementById("grafico-solicitudes-registro").getContext('2d');
                        var myChart = new Chart(ctx, {
                        type: 'bar',
                        data: {
                            labels: [{% for clave in dict_curso_numregistro %} "{{ clave }}", {% endfor %}],
                            datasets: [{
                                label: '# Solicitudes de Registo por curso',
                                data: [{% for valor in dict_curso_numregistro.values %} {{ valor}}, {% endfor %}],
                                backgroundColor: [
                                    'rgba(255, 99, 132, 1)',
                                    'rgba(54, 162, 235, 1)',
                                    'rgba(255, 206, 86, 1)',
                                    'rgba(75, 192, 192, 1)',
                                    'rgba(153, 102, 255, 1)',
                                    'rgba(255, 159, 64, 1)',
                                    'rgba(124, 252, 0,1)',
                                    'rgba(235, 215, 0,1)'
                                ],
                                borderColor: [
                                    'rgba(255,99,132,1)',
                                    'rgba(54, 162, 235, 1)',
                                    'rgba(255, 206, 86, 1)',
                                    'rgba(75, 192, 192, 1)',
                                    'rgba(153, 102, 255, 1)',
                                    'rgba(255, 159, 64, 1)',
                                    'rgba(124, 252, 0,1)',
                                    'rgba(235, 215, 0,1)'
                                ],
                                borderWidth: 1
                            }]
                        },
                         options: {
                            scales: {
                                yAxes: [{
                                    display: true,
                                    ticks: {
                                        beginAtZero:true,
                                        stepSize: 1 
                                    }
                                }]
                                }
                            }
                        }); 
                        </script>  
                       {% endif %} 
                </div>
                <BR>
                <div class="rep-div rep-tabla">
                    <div class="tabla-repo">
                        <table id="AreasDeInteres" class="displa table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Usuario</th>
                                    <th>teléfono</th>
                                    <th>email</th>
                                    <th>fecha solicitud</th>
                                    <th>Curso</th>

                                </tr>
                            </thead>
                            <tbody> 
                                {% for registro in dict_info_tabla %}
                                <tr>
                                    <td>{{registro.usuario_id.id}}</td>
                                    <td>{{registro.usuario_id.username}}</td>
                                    <td>{% for telefono in registro.usuario_id.telefonos_set.all %}
                                         {{telefono.telefonos}},
                                        {% endfor %}</td>
                                    <td>{{registro.usuario_id.email}}</td>
                                    <td>{{registro.usuario_id.date_joined}} </td>
                                    <td>{{registro.curso_id.nombre}} </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Id</th>
                                    <th>Usuario</th>
                                    <th>teléfono</th>
                                    <th>email</th>
                                    <th>fecha solicitud</th>
                                </tr>
                            </tfoot>
                        </table>
                </div>
            </div>
                <div class="rep-div rep-expo">
                    <p style="text-align: center;">
                        <a  href="{% url 'reportes_xlsx' reporte=2 curso=0 %}">
                            <button type="button" class="btn btn-success">Exportar Reporte</button>
                        </a>
                    </p>
                </div>
            </div>
        </div>
 </div>
{% endblock %}
{% block extraScript %}

    <script src="{% static 'js/reporte.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('table#AreasDeInteres').DataTable();
        } );
    </script>

{% endblock %}